[package]
name = "remote_attr"
version = "0.1.0"
authors = ["Craig Wilkinson <craig@crwi.uk>"]
edition = "2020"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.46", features = ["full", "extra-traits"] }
quote = "1.0.7"
proc-macro2 = "0.4.30"

[features]

frontend = []
backend = []